name: Deploy on ftp server mmi

on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: unbuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: deploy on mmi server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER}}
          password: ${{ secrets.SERVER_PASSWORD }}
          local-dir: ./sae501plugin.php
          server-dir: /httpdocs/wp-content/plugins/sae501/ 

 
